[build]
builder = "NIXPACKS"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["go_1_22"]

# Явно вказуємо, ЯК зібрати проєкт
[build.nixpacksPlan.phases.build]
cmds = ["go build -o server_bin cmd/server/main.go"]

[deploy]
# Запускаємо вже скомпільований файл (без команди 'go')
startCommand = "./server_bin"
restartPolicyType = "ON_FAILURE"